Repository HynssFashionLog/Fashion-Log, pull requests merged in 2024-08, with the labels that each got.

#112 Design: FreeBoard html 변경
  src/main/java/com/example/fashionlog/controller/FreeBoardController.java
  src/main/resources/templates/freeboard/detail.html
  src/main/resources/templates/freeboard/form.html
  src/main/resources/templates/freeboard/list.html
Labels: 🎨 design

#114 Refactor: Lookbook 코드 전체 리팩터링
  src/main/java/com/example/fashionlog/controller/LookbookController.java
  src/main/java/com/example/fashionlog/domain/Lookbook.java
  src/main/java/com/example/fashionlog/domain/LookbookComment.java
  src/main/java/com/example/fashionlog/dto/LookbookCommentDto.java
  src/main/java/com/example/fashionlog/dto/LookbookDto.java
  src/main/java/com/example/fashionlog/repository/LookbookCommentRepository.java
  src/main/java/com/example/fashionlog/repository/LookbookRepository.java
  src/main/java/com/example/fashionlog/service/LookbookService.java
  src/main/resources/static/lookbook/css/detail.css
  src/main/resources/static/lookbook/css/edit-form.css
  src/main/resources/static/lookbook/css/list.css
  src/main/resources/static/lookbook/css/styles.css
  src/main/resources/static/lookbook/js/detail.js
  src/main/resources/templates/lookbook/detail.html
  src/main/resources/templates/lookbook/editForm.html
  src/main/resources/templates/lookbook/list.html
  src/main/resources/templates/lookbook/new.html
Labels: ⚒️ refactor

#116 Docs: dev yml 배포용으로 수정 (불필요한 설정 제거)
  src/main/resources/application-dev.yml
Labels: 📚 documentation

#120 Feat: 로그인 및 회원가입 기능 구현
  build.gradle
  src/main/java/com/example/fashionlog/controller/MainController.java
  src/main/java/com/example/fashionlog/controller/user/LoginController.java
  src/main/java/com/example/fashionlog/controller/user/SignUpController.java
  src/main/java/com/example/fashionlog/domain/Member.java
  src/main/java/com/example/fashionlog/dto/MemberDto.java
  src/main/java/com/example/fashionlog/repository/MemberRepository.java
  src/main/java/com/example/fashionlog/service/MemberService.java
  src/main/resources/static/css/login.css
  src/main/resources/static/css/styles.css
  src/main/resources/templates/home.html
  src/main/resources/templates/login.html
  src/main/resources/templates/sign-up.html
Labels: ✨ feature

#121 Feat: Spring Security 핵심 구성 요소 구현
  src/main/java/com/example/fashionlog/PasswordEncoderConfig.java
  src/main/java/com/example/fashionlog/SecurityConfig.java
  src/main/java/com/example/fashionlog/service/CustomUserDetailsService.java
Labels: ✨ feature

#123 Design: home, sign-up 스타일적용
  src/main/resources/static/css/home.css
  src/main/resources/static/css/sign-up.css
  src/main/resources/templates/home.html
  src/main/resources/templates/sign-up.html
Labels: 🎨 design

#125 Refactor: static 파일 구조 최적화 및 중복 제거
  src/main/resources/static/css/board/detail.css
  src/main/resources/static/css/board/edit-form.css
  src/main/resources/static/css/board/list.css
  src/main/resources/static/dailylook/css/styles.css
  src/main/resources/static/freeboard/css/detail.css
  src/main/resources/static/freeboard/css/edit-form.css
  src/main/resources/static/freeboard/css/styles.css
  src/main/resources/static/freeboard/js/detail.js
  src/main/resources/static/interview/css/detail.css
  src/main/resources/static/interview/css/edit-form.css
  src/main/resources/static/interview/css/list.css
  src/main/resources/static/interview/css/styles.css
  src/main/resources/static/interview/js/detail.js
  src/main/resources/static/js/detail.js
  src/main/resources/static/lookbook.css
  src/main/resources/static/lookbook/css/detail.css
  src/main/resources/static/lookbook/css/edit-form.css
  src/main/resources/static/lookbook/css/list.css
  src/main/resources/static/lookbook/css/styles.css
  src/main/resources/static/lookbook/js/detail.js
  src/main/resources/static/style.css
  src/main/resources/templates/dailylook/detail.html
  src/main/resources/templates/dailylook/edit.html
  src/main/resources/templates/dailylook/form.html
  src/main/resources/templates/dailylook/list.html
  src/main/resources/templates/freeboard/detail.html
  src/main/resources/templates/freeboard/edit.html
  src/main/resources/templates/freeboard/form.html
  src/main/resources/templates/freeboard/list.html
  src/main/resources/templates/header.html
  src/main/resources/templates/home.html
  src/main/resources/templates/interviewboard/detail.html
  src/main/resources/templates/interviewboard/edit.html
  src/main/resources/templates/interviewboard/form.html
  src/main/resources/templates/interviewboard/list.html
  src/main/resources/templates/login.html
  src/main/resources/templates/lookbook/detail.html
  src/main/resources/templates/lookbook/editForm.html
  src/main/resources/templates/lookbook/list.html
  src/main/resources/templates/lookbook/new.html
Labels: ⚒️ refactor

#128 Feat: 공지사항 게시판과 댓글 기능 구현
  src/main/java/com/example/fashionlog/SecurityConfig.java
  src/main/java/com/example/fashionlog/controller/NoticeController.java
  src/main/java/com/example/fashionlog/domain/Category.java
  src/main/java/com/example/fashionlog/domain/Notice.java
  src/main/java/com/example/fashionlog/domain/NoticeComment.java
  src/main/java/com/example/fashionlog/domain/NoticeUpdatable.java
  src/main/java/com/example/fashionlog/dto/NoticeCommentDto.java
  src/main/java/com/example/fashionlog/dto/NoticeDto.java
  src/main/java/com/example/fashionlog/repository/NoticeCommentRepository.java
  src/main/java/com/example/fashionlog/repository/NoticeRepository.java
  src/main/java/com/example/fashionlog/service/NoticeService.java
  src/main/resources/static/notice/css/detail.css
  src/main/resources/static/notice/css/edit-form.css
  src/main/resources/static/notice/css/list.css
  src/main/resources/static/notice/css/styles.css
  src/main/resources/static/notice/js/detail.js
  src/main/resources/templates/notice/detail.html
  src/main/resources/templates/notice/edit.html
  src/main/resources/templates/notice/form.html
  src/main/resources/templates/notice/list.html
Labels: ✨ feature

#130 Feat: 게시판과 댓글 Base Entity에 member id 추가
  src/main/java/com/example/fashionlog/domain/BaseEntity.java
  src/main/java/com/example/fashionlog/domain/CommentBaseEntity.java
  src/main/java/com/example/fashionlog/domain/Member.java
Labels: ✨ feature

#131 Feat: 자유 게시판과 댓글에 본인이 쓴 글이거나 관리자 일 때만 수정 및 삭제가 가능하도록 코드 추가
  src/main/java/com/example/fashionlog/controller/FreeBoardController.java
  src/main/java/com/example/fashionlog/dto/FreeBoardCommentDto.java
  src/main/java/com/example/fashionlog/dto/FreeBoardDto.java
  src/main/java/com/example/fashionlog/service/FreeBoardService.java
Labels: ✨ feature

#134 Refactor: 권한 검사 시스템 개선 및 DailyLook 게시판 전반적인 리펙터링
  src/main/java/com/example/fashionlog/SecurityConfig.java
  src/main/java/com/example/fashionlog/aop/AuthCheck.java
  src/main/java/com/example/fashionlog/aop/AuthorType.java
  src/main/java/com/example/fashionlog/aop/AuthorizationAspect.java
  src/main/java/com/example/fashionlog/domain/BaseEntity.java
  src/main/java/com/example/fashionlog/domain/CommentBaseEntity.java
  src/main/java/com/example/fashionlog/domain/PersistentLogins.java
  src/main/java/com/example/fashionlog/dto/DailyLookCommentDto.java
  src/main/java/com/example/fashionlog/dto/DailyLookDto.java
  src/main/java/com/example/fashionlog/security/PasswordEncoderConfig.java
  src/main/java/com/example/fashionlog/security/SecurityConfig.java
  src/main/java/com/example/fashionlog/security/SecurityUtil.java
  src/main/java/com/example/fashionlog/service/BoardService.java
  src/main/java/com/example/fashionlog/service/CurrentUserProvider.java
  src/main/java/com/example/fashionlog/service/DailyLookService.java
Labels: ⚒️ refactor

#137 Feat: Trade 게시판 생성
  src/main/java/com/example/fashionlog/controller/TradeController.java
  src/main/java/com/example/fashionlog/domain/Trade.java
  src/main/java/com/example/fashionlog/domain/TradeComment.java
  src/main/java/com/example/fashionlog/dto/TradeCommentDto.java
  src/main/java/com/example/fashionlog/dto/TradeDto.java
  src/main/java/com/example/fashionlog/repository/TradeCommentRepository.java
  src/main/java/com/example/fashionlog/repository/TradeRepository.java
  src/main/java/com/example/fashionlog/service/TradeService.java
  src/main/resources/static/trade/css/detail.css
  src/main/resources/static/trade/css/edit-form.css
  src/main/resources/static/trade/css/list.css
  src/main/resources/static/trade/css/styles.css
  src/main/resources/static/trade/js/detail.js
  src/main/resources/templates/trade/detail.html
  src/main/resources/templates/trade/editForm.html
  src/main/resources/templates/trade/list.html
  src/main/resources/templates/trade/new.html
Labels: ✨ feature

#138 Refactor: AuthorizationAspect 에 각 게시판 의존성 주석으로 추가
  src/main/java/com/example/fashionlog/aop/AuthorizationAspect.java
Labels: ⚒️ refactor

#139 Refactor: 추가된 Member 코드에 관한 InterviewBoard, Notice 리팩토링
  src/main/java/com/example/fashionlog/dto/InterviewBoardCommentDto.java
  src/main/java/com/example/fashionlog/dto/InterviewBoardDto.java
  src/main/java/com/example/fashionlog/dto/NoticeCommentDto.java
  src/main/java/com/example/fashionlog/dto/NoticeDto.java
  src/main/java/com/example/fashionlog/service/InterviewBoardService.java
  src/main/java/com/example/fashionlog/service/NoticeService.java
Labels: ⚒️ refactor

#140 Refactor: 추가된 Member 코드에 관한 Lookbook, Trade 리팩토링
  src/main/java/com/example/fashionlog/dto/LookbookCommentDto.java
  src/main/java/com/example/fashionlog/dto/LookbookDto.java
  src/main/java/com/example/fashionlog/dto/TradeCommentDto.java
  src/main/java/com/example/fashionlog/dto/TradeDto.java
  src/main/java/com/example/fashionlog/service/LookbookService.java
  src/main/java/com/example/fashionlog/service/TradeService.java
Labels: ⚒️ refactor

#141 Refactor: Header 레이아웃 및 CSS, HTML 구조 개선
  src/main/resources/static/css/board/detail.css
  src/main/resources/static/css/home.css
  src/main/resources/static/css/login.css
  src/main/resources/static/css/styles.css
  src/main/resources/static/notice/css/detail.css
  src/main/resources/static/notice/css/edit-form.css
  src/main/resources/static/notice/js/detail.js
  src/main/resources/static/trade/css/detail.css
  src/main/resources/static/trade/css/edit-form.css
  src/main/resources/static/trade/js/detail.js
  src/main/resources/templates/dailylook/detail.html
  src/main/resources/templates/header.html
  src/main/resources/templates/notice/detail.html
  src/main/resources/templates/notice/edit.html
  src/main/resources/templates/notice/form.html
  src/main/resources/templates/trade/detail.html
  src/main/resources/templates/trade/editForm.html
  src/main/resources/templates/trade/new.html
Labels: ⚒️ refactor

#145 Feat: 회원가입 페이지 중복 확인 기능 추가
  src/main/java/com/example/fashionlog/controller/user/SignUpController.java
  src/main/java/com/example/fashionlog/repository/MemberRepository.java
  src/main/java/com/example/fashionlog/security/SecurityConfig.java
  src/main/java/com/example/fashionlog/service/MemberService.java
  src/main/resources/static/css/sign-up.css
  src/main/resources/templates/sign-up.html
Labels: ✨ feature

#142 Feat: 각 카테고리별 게시판에 해당되는 공지사항 최신순 5개만 볼 수 있도록 구현
  src/main/java/com/example/fashionlog/controller/DailyLookController.java
  src/main/java/com/example/fashionlog/controller/FreeBoardController.java
  src/main/java/com/example/fashionlog/controller/InterviewBoardController.java
  src/main/java/com/example/fashionlog/controller/LookbookController.java
  src/main/java/com/example/fashionlog/controller/TradeController.java
  src/main/java/com/example/fashionlog/repository/NoticeRepository.java
  src/main/java/com/example/fashionlog/service/NoticeService.java
  src/main/resources/static/css/board/list.css
  src/main/resources/templates/dailylook/list.html
  src/main/resources/templates/freeboard/list.html
  src/main/resources/templates/interviewboard/list.html
  src/main/resources/templates/lookbook/list.html
  src/main/resources/templates/trade/list.html
Labels: ✨ feature

#143 Feat: 관리자만 회원 권한 수정하기 기능 추가
  src/main/java/com/example/fashionlog/controller/user/AdminUserManagementController.java
  src/main/java/com/example/fashionlog/security/SecurityConfig.java
  src/main/java/com/example/fashionlog/service/MemberService.java
  src/main/resources/templates/management.html
Labels: ✨ feature

#146 Refactor: 필요없는 TEST 삭제
  src/test/java/com/example/fashionlog/FashionLogApplicationTests.java
Labels: ⚒️ refactor

#149 Enhancement: ADMIN 권한이 있으면 모든 글을 수정 / 삭제 할 수 있도록 코드 추가
  src/main/java/com/example/fashionlog/aop/AuthorizationAspect.java
  src/main/java/com/example/fashionlog/controller/FreeBoardController.java
  src/main/java/com/example/fashionlog/service/FreeBoardService.java
  src/main/java/com/example/fashionlog/service/MemberService.java
Labels: 🐞 bug, 💪 enhancement, ⚒️ refactor

#150 Docs: db password 변경
  src/main/resources/application-dev.yml
Labels: 📚 documentation

#155 Docs: Trade 게시판 css수정, Trade, Lookbook게시판 글 댓글 권한 재설정
  src/main/java/com/example/fashionlog/service/LookbookService.java
  src/main/java/com/example/fashionlog/service/TradeService.java
  src/main/resources/templates/trade/detail.html
  src/main/resources/templates/trade/editForm.html
  src/main/resources/templates/trade/list.html
Labels: 📚 documentation

#156 Refactor: 각 게시판 작성자 이름 표시 기능 구현
  src/main/java/com/example/fashionlog/dto/DailyLookCommentDto.java
  src/main/java/com/example/fashionlog/dto/DailyLookDto.java
  src/main/java/com/example/fashionlog/dto/FreeBoardCommentDto.java
  src/main/java/com/example/fashionlog/dto/FreeBoardDto.java
  src/main/java/com/example/fashionlog/dto/InterviewBoardCommentDto.java
  src/main/java/com/example/fashionlog/dto/InterviewBoardDto.java
  src/main/java/com/example/fashionlog/dto/LookbookCommentDto.java
  src/main/java/com/example/fashionlog/dto/LookbookDto.java
  src/main/java/com/example/fashionlog/dto/NoticeCommentDto.java
  src/main/java/com/example/fashionlog/dto/NoticeDto.java
  src/main/java/com/example/fashionlog/service/DailyLookService.java
  src/main/java/com/example/fashionlog/service/FreeBoardService.java
  src/main/java/com/example/fashionlog/service/InterviewBoardService.java
  src/main/java/com/example/fashionlog/service/LookbookService.java
  src/main/java/com/example/fashionlog/service/NoticeService.java
  src/main/resources/templates/dailylook/detail.html
  src/main/resources/templates/dailylook/list.html
  src/main/resources/templates/freeboard/detail.html
  src/main/resources/templates/freeboard/list.html
  src/main/resources/templates/interviewboard/detail.html
  src/main/resources/templates/interviewboard/list.html
  src/main/resources/templates/lookbook/detail.html
  src/main/resources/templates/lookbook/list.html
  src/main/resources/templates/notice/detail.html
  src/main/resources/templates/notice/list.html
Labels: ⚒️ refactor

#158 Feat: 회원가입 시 휴대폰번호 형식 지정
  src/main/java/com/example/fashionlog/controller/user/SignUpController.java
  src/main/java/com/example/fashionlog/service/MemberService.java
  src/main/resources/templates/sign-up.html
Labels: ✨ feature

#162 Refactor: 공지사항 게시판 전반적인 리팩토링
  src/main/resources/static/css/board/list.css
  src/main/resources/templates/dailylook/list.html
  src/main/resources/templates/freeboard/list.html
  src/main/resources/templates/interviewboard/list.html
  src/main/resources/templates/lookbook/list.html
  src/main/resources/templates/notice/list.html
  src/main/resources/templates/trade/list.html
Labels: ⚒️ refactor

#164 Refactor: Interview, Notice 권한체크 리팩토링
  src/main/java/com/example/fashionlog/aop/AuthorizationAspect.java
  src/main/java/com/example/fashionlog/service/board/InterviewBoardService.java
  src/main/java/com/example/fashionlog/service/board/NoticeService.java
Labels: ⚒️ refactor

#165 Feat: 권한이 없는 사용자에게는 수정 / 삭제 버튼 안 보이게 하기
  src/main/java/com/example/fashionlog/dto/board/DailyLookDto.java
  src/main/java/com/example/fashionlog/dto/board/FreeBoardDto.java
  src/main/java/com/example/fashionlog/dto/board/InterviewBoardDto.java
  src/main/java/com/example/fashionlog/dto/board/LookbookDto.java
  src/main/java/com/example/fashionlog/dto/board/TradeDto.java
  src/main/java/com/example/fashionlog/dto/comment/DailyLookCommentDto.java
  src/main/java/com/example/fashionlog/dto/comment/FreeBoardCommentDto.java
  src/main/java/com/example/fashionlog/dto/comment/InterviewBoardCommentDto.java
  src/main/java/com/example/fashionlog/dto/comment/LookbookCommentDto.java
  src/main/java/com/example/fashionlog/dto/comment/NoticeCommentDto.java
  src/main/java/com/example/fashionlog/dto/comment/TradeCommentDto.java
  src/main/java/com/example/fashionlog/service/board/DailyLookService.java
  src/main/java/com/example/fashionlog/service/board/FreeBoardService.java
  src/main/java/com/example/fashionlog/service/board/InterviewBoardService.java
  src/main/java/com/example/fashionlog/service/board/LookbookService.java
  src/main/java/com/example/fashionlog/service/board/NoticeService.java
  src/main/java/com/example/fashionlog/service/board/TradeService.java
  src/main/resources/templates/dailylook/detail.html
  src/main/resources/templates/freeboard/detail.html
  src/main/resources/templates/interviewboard/detail.html
  src/main/resources/templates/lookbook/detail.html
  src/main/resources/templates/notice/detail.html
  src/main/resources/templates/trade/detail.html
Labels: ✨ feature

#167 Fix: Lookbook, Trade 게시판 댓글 수정 오류 수정
  src/main/java/com/example/fashionlog/service/board/LookbookService.java
  src/main/java/com/example/fashionlog/service/board/TradeService.java
Labels: 🐞 bug

#169 Docs: list.html 새 글 작성 버튼 우측 상단으로 위치 조정
  src/main/resources/static/css/board/list.css
  src/main/resources/templates/dailylook/list.html
  src/main/resources/templates/freeboard/list.html
  src/main/resources/templates/interviewboard/list.html
  src/main/resources/templates/lookbook/list.html
  src/main/resources/templates/notice/list.html
  src/main/resources/templates/trade/list.html
Labels: 📚 documentation

#170 Refactor: 전반적인 헤더 리팩토링
  src/main/java/com/example/fashionlog/service/CustomUserDetails.java
  src/main/java/com/example/fashionlog/service/CustomUserDetailsService.java
  src/main/resources/static/css/management.css
  src/main/resources/static/img/hynss-logo.png
  src/main/resources/templates/header.html
  src/main/resources/templates/management.html
Labels: 💪 enhancement, ⚒️ refactor

#173 Enhancement: 전반적인 예외 처리
  build.gradle
  src/main/java/com/example/fashionlog/aop/auth/AuthCheck.java
  src/main/java/com/example/fashionlog/aop/auth/AuthorType.java
  src/main/java/com/example/fashionlog/aop/auth/AuthorizationAspect.java
  src/main/java/com/example/fashionlog/aop/exception/BoardExceptionHandler.java
  src/main/java/com/example/fashionlog/aop/exception/ExceptionAspect.java
  src/main/java/com/example/fashionlog/controller/board/DailyLookController.java
  src/main/java/com/example/fashionlog/controller/board/FreeBoardController.java
  src/main/java/com/example/fashionlog/controller/board/InterviewBoardController.java
  src/main/java/com/example/fashionlog/controller/board/LookbookController.java
  src/main/java/com/example/fashionlog/controller/board/NoticeController.java
  src/main/java/com/example/fashionlog/controller/board/TradeController.java
  src/main/java/com/example/fashionlog/dto/MemberDto.java
  src/main/java/com/example/fashionlog/dto/board/DailyLookDto.java
  src/main/java/com/example/fashionlog/dto/board/FreeBoardDto.java
  src/main/java/com/example/fashionlog/dto/board/InterviewBoardDto.java
  src/main/java/com/example/fashionlog/dto/board/LookbookDto.java
  src/main/java/com/example/fashionlog/dto/board/NoticeDto.java
  src/main/java/com/example/fashionlog/dto/board/TradeDto.java
  src/main/java/com/example/fashionlog/dto/comment/DailyLookCommentDto.java
  src/main/java/com/example/fashionlog/dto/comment/FreeBoardCommentDto.java
  src/main/java/com/example/fashionlog/dto/comment/InterviewBoardCommentDto.java
  src/main/java/com/example/fashionlog/dto/comment/LookbookCommentDto.java
  src/main/java/com/example/fashionlog/dto/comment/NoticeCommentDto.java
  src/main/java/com/example/fashionlog/dto/comment/TradeCommentDto.java
  src/main/java/com/example/fashionlog/repository/board/InterviewBoardRepository.java
  src/main/java/com/example/fashionlog/security/SecurityConfig.java
  src/main/java/com/example/fashionlog/service/board/DailyLookService.java
  src/main/java/com/example/fashionlog/service/board/FreeBoardService.java
  src/main/java/com/example/fashionlog/service/board/InterviewBoardService.java
  src/main/java/com/example/fashionlog/service/board/LookbookService.java
  src/main/java/com/example/fashionlog/service/board/NoticeService.java
  src/main/java/com/example/fashionlog/service/board/TradeService.java
  src/main/resources/static/trade/css/list.css
  src/main/resources/static/trade/css/styles.css
  src/main/resources/templates/notice/edit.html
  src/main/resources/templates/notice/form.html
  src/main/resources/templates/trade/list.html
Labels: 🐞 bug, 💪 enhancement, ⚒️ refactor, 👷‍♂️ chore

#176 Docs: 로그인, 회원가입 페이지 로고이미지 활성화
  src/main/java/com/example/fashionlog/security/SecurityConfig.java
  src/main/resources/templates/login.html
  src/main/resources/templates/sign-up.html
Labels: 📚 documentation

#177 Refactor: 관리자 페이지 회원 목록에 관리자 제외
  src/main/java/com/example/fashionlog/repository/MemberRepository.java
  src/main/java/com/example/fashionlog/service/MemberService.java
  src/main/java/com/example/fashionlog/service/board/NoticeService.java
  src/main/resources/templates/management.html
Labels: ⚒️ refactor

#180 Design: 메인 페이지에 게시판 이미지 크기 수정, hover추가
  src/main/resources/static/css/home.css
Labels: 🎨 design

#181 Create README.md
  README.md
Labels: 📚 documentation

#182 Update README.md
  README.md
Labels: 📚 documentation
