Repository HynssFashionLog/Fashion-Log, pull requests merged in 2024-07, with the labels that each got.

#1 Feat: initial commit
  src/main/java/com/example/fashionlog/Controller/Controller.java
  src/main/java/com/example/fashionlog/DTO/Dto.java
  src/main/java/com/example/fashionlog/Domain/Domain.java
  src/main/java/com/example/fashionlog/Repository/Repository.java
  src/main/java/com/example/fashionlog/Service/Service.java
Labels: 👷‍♂️ chore

#4 Docs: issue template 추가
  .github/ISSUE_TEMPLATE/custom.md
Labels: 📚 documentation

#5 Docs: PR 템플릿 이름 변경 및 주석 삭제
  .github/PULL_REQUEST_TEMPLATE.md
  .github/pull_request_template.md
Labels: 📚 documentation

#6 Docs: Issue Template 수정
  .github/ISSUE_TEMPLATE/custom.md
Labels: 📚 documentation

#7 Docs: featue template 추가
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: 📚 documentation

#9 Docs: gitignore 작성 및 template, static 디렉토리 추가
  .gitignore
  src/main/java/com/example/fashionlog/controller/Controller.java
  src/main/java/com/example/fashionlog/domain/Domain.java
  src/main/java/com/example/fashionlog/dto/Dto.java
  src/main/java/com/example/fashionlog/repository/Repository.java
  src/main/java/com/example/fashionlog/service/Service.java
  src/main/resources/static/style.css
  src/main/resources/template/page.html
Labels: 📚 documentation

#13 Feat: Member Entity 추가
  src/main/java/com/example/fashionlog/domain/Member.java
  src/main/java/com/example/fashionlog/domain/Role.java
  src/main/java/com/example/fashionlog/dto/Dto.java
  src/main/java/com/example/fashionlog/dto/MemberDto.java
Labels: ✨ feature

#15 Docs: gitignore 변경
  .gitignore
  src/main/java/com/example/fashionlog/dto/Dto.java
  src/main/resources/application-dev.yml
Labels: 📚 documentation

#17 Docs: application-dev.yml 추가
  .gitignore
  src/main/resources/application-dev.yml
Labels: 📚 documentation

#19 Docs: gitignore .idea 추가
  .gitignore
Labels: 📚 documentation

#21 Feat: FreeBoard 자유 게시판 조회 기능 구현
  src/main/java/com/example/fashionlog/controller/FreeBoardController.java
  src/main/java/com/example/fashionlog/domain/FreeBoard.java
  src/main/java/com/example/fashionlog/domain/FreeBoardComment.java
  src/main/java/com/example/fashionlog/dto/FreeBoardCommentDto.java
  src/main/java/com/example/fashionlog/dto/FreeBoardDto.java
  src/main/java/com/example/fashionlog/repository/FreeBoardCommentRepository.java
  src/main/java/com/example/fashionlog/repository/FreeBoardRepository.java
  src/main/java/com/example/fashionlog/service/FreeBoardService.java
  src/main/resources/templates/freeboard/list.html
  src/main/resources/templates/page.html
Labels: ✨ feature

#23 Feat: DailyLook 게시판 조회 기능 구현
  src/main/java/com/example/fashionlog/controller/DailyLookController.java
  src/main/java/com/example/fashionlog/domain/DailyLook.java
  src/main/java/com/example/fashionlog/dto/DailyLookDto.java
  src/main/java/com/example/fashionlog/repository/DailyLookRepository.java
  src/main/java/com/example/fashionlog/service/DailyLookService.java
  src/main/resources/templates/dailylook/list.html
Labels: ✨ feature

#27 Feat: InterviewBoard 조회 기능 추가
  src/main/java/com/example/fashionlog/controller/InterviewBoardController.java
  src/main/java/com/example/fashionlog/domain/InterviewBoard.java
  src/main/java/com/example/fashionlog/dto/InterviewBoardDto.java
  src/main/java/com/example/fashionlog/repository/InterviewBoardRepository.java
  src/main/java/com/example/fashionlog/service/InterviewBoardService.java
  src/main/resources/templates/interviewboard/list.html
Labels: ✨ feature

#29 Feat: FreeBoard 자유 게시판 글 작성하기 기능 구현
  src/main/java/com/example/fashionlog/controller/FreeBoardController.java
  src/main/java/com/example/fashionlog/domain/FreeBoard.java
  src/main/java/com/example/fashionlog/dto/FreeBoardDto.java
  src/main/java/com/example/fashionlog/service/DailyLookService.java
  src/main/java/com/example/fashionlog/service/FreeBoardService.java
  src/main/resources/templates/freeboard/form.html
  src/main/resources/templates/freeboard/list.html
Labels: ✨ feature

#31 Feat: DailyLook 글 작성 기능 구현
  src/main/java/com/example/fashionlog/controller/DailyLookController.java
  src/main/java/com/example/fashionlog/dto/DailyLookDto.java
  src/main/java/com/example/fashionlog/service/DailyLookService.java
  src/main/resources/templates/dailylook/form.html
  src/main/resources/templates/dailylook/list.html
Labels: ✨ feature

#33 Feat: FreeBoard 자유 게시판 글 상세보기 기능 구현
  src/main/java/com/example/fashionlog/controller/FreeBoardController.java
  src/main/java/com/example/fashionlog/service/FreeBoardService.java
  src/main/resources/templates/freeboard/detail.html
  src/main/resources/templates/freeboard/list.html
Labels: ✨ feature

#38 Feat: InterviewBoard 새 글 작성 기능 추가
  src/main/java/com/example/fashionlog/controller/InterviewBoardController.java
  src/main/java/com/example/fashionlog/dto/InterviewBoardDto.java
  src/main/java/com/example/fashionlog/service/InterviewBoardService.java
  src/main/resources/templates/interviewboard/form.html
  src/main/resources/templates/interviewboard/list.html
Labels: ✨ feature

#39 Feat: FreeBoard 자유 게시판 글 수정하기 구현
  src/main/java/com/example/fashionlog/controller/FreeBoardController.java
  src/main/java/com/example/fashionlog/domain/FreeBoard.java
  src/main/java/com/example/fashionlog/service/FreeBoardService.java
  src/main/resources/templates/freeboard/detail.html
  src/main/resources/templates/freeboard/edit.html
  src/main/resources/templates/freeboard/form.html
  src/main/resources/templates/page.html
Labels: ✨ feature

#41 Feat: FreeBoard 자유 게시판 글 삭제하기 구현
  src/main/java/com/example/fashionlog/controller/FreeBoardController.java
  src/main/java/com/example/fashionlog/service/FreeBoardService.java
Labels: ✨ feature

#43 Feat: DailyLook 게시판 글 수정 기능 구현
  src/main/java/com/example/fashionlog/controller/DailyLookController.java
  src/main/java/com/example/fashionlog/domain/DailyLook.java
  src/main/java/com/example/fashionlog/dto/DailyLookDto.java
  src/main/java/com/example/fashionlog/service/DailyLookService.java
  src/main/resources/templates/dailylook/detail.html
  src/main/resources/templates/dailylook/edit.html
  src/main/resources/templates/dailylook/list.html
Labels: ✨ feature

#45 Feat: DailyLook 게시판 글 삭제 기능 구현
  src/main/java/com/example/fashionlog/controller/DailyLookController.java
  src/main/java/com/example/fashionlog/service/DailyLookService.java
  src/main/resources/templates/dailylook/detail.html
  src/main/resources/templates/dailylook/edit.html
  src/main/resources/templates/dailylook/list.html
Labels: ✨ feature

#47 Feat: InterviewBoard 게시글 상세 조회 기능 추가
  src/main/java/com/example/fashionlog/controller/InterviewBoardController.java
  src/main/java/com/example/fashionlog/service/InterviewBoardService.java
  src/main/resources/templates/interviewboard/detail.html
  src/main/resources/templates/interviewboard/list.html
Labels: ✨ feature

#50 Feat: FreeBoard 자유 게시판 댓글 조회하기 구현
  src/main/java/com/example/fashionlog/controller/FreeBoardController.java
  src/main/java/com/example/fashionlog/domain/FreeBoardComment.java
  src/main/java/com/example/fashionlog/dto/FreeBoardCommentDto.java
  src/main/java/com/example/fashionlog/repository/FreeBoardCommentRepository.java
  src/main/java/com/example/fashionlog/service/FreeBoardService.java
  src/main/resources/templates/freeboard/detail.html
Labels: ✨ feature

#52 Refactor: DailyLookService @Transactional 어노테이션 메서드 레벨 적용
  src/main/java/com/example/fashionlog/service/DailyLookService.java
Labels: ⚒️ refactor

#53 Feat: FreeBoard 자유 게시판 댓글 생성하기 구현
  src/main/java/com/example/fashionlog/controller/FreeBoardController.java
  src/main/java/com/example/fashionlog/domain/FreeBoardComment.java
  src/main/java/com/example/fashionlog/dto/FreeBoardCommentDto.java
  src/main/java/com/example/fashionlog/service/FreeBoardService.java
  src/main/resources/templates/freeboard/detail.html
Labels: ✨ feature

#55 Feat: InterviewBoard 게시글 수정 기능 추가
  src/main/java/com/example/fashionlog/controller/InterviewBoardController.java
  src/main/java/com/example/fashionlog/domain/InterviewBoard.java
  src/main/java/com/example/fashionlog/service/InterviewBoardService.java
  src/main/resources/templates/interviewboard/detail.html
  src/main/resources/templates/interviewboard/edit.html
Labels: ✨ feature

#56 Feat: DailyLook 댓글 조회 및 생성 기능 구현
  src/main/java/com/example/fashionlog/controller/DailyLookController.java
  src/main/java/com/example/fashionlog/domain/DailyLook.java
  src/main/java/com/example/fashionlog/dto/DailyLookCommentDto.java
  src/main/java/com/example/fashionlog/repository/DailyLookCommentRepository.java
  src/main/java/com/example/fashionlog/service/DailyLookService.java
  src/main/resources/templates/dailylook/detail.html
Labels: ✨ feature

#58 Docs: Update issue templates
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: 📚 documentation

#60 Feat: Lookbook 게시판 구현
  src/main/java/com/example/fashionlog/controller/LookbookController.java
  src/main/java/com/example/fashionlog/domain/Lookbook.java
  src/main/java/com/example/fashionlog/dto/LookbookDto.java
  src/main/java/com/example/fashionlog/repository/LookbookRepository.java
  src/main/java/com/example/fashionlog/service/LookbookService.java
  src/main/resources/static/lookbook.css
  src/main/resources/templates/lookbook/detail.html
  src/main/resources/templates/lookbook/editForm.html
  src/main/resources/templates/lookbook/list.html
  src/main/resources/templates/lookbook/new.html
Labels: ✨ feature

#61 Feat: InterviewBoard 게시글 삭제하기 기능 구현
  src/main/java/com/example/fashionlog/controller/InterviewBoardController.java
  src/main/java/com/example/fashionlog/domain/InterviewBoard.java
  src/main/java/com/example/fashionlog/service/InterviewBoardService.java
  src/main/resources/templates/interviewboard/detail.html
  src/main/resources/templates/interviewboard/list.html
Labels: ✨ feature

#63 Docs: LookbookDto, Service 수정
  src/main/java/com/example/fashionlog/dto/LookbookDto.java
  src/main/java/com/example/fashionlog/service/LookbookService.java
Labels: 📚 documentation

#64 Feat: FreeBoard 자유 게시판 댓글 수정하기 구현
  src/main/java/com/example/fashionlog/controller/FreeBoardController.java
  src/main/java/com/example/fashionlog/domain/FreeBoardComment.java
  src/main/java/com/example/fashionlog/service/FreeBoardService.java
  src/main/resources/templates/freeboard/detail.html
Labels: ⚒️ refactor, ✨ feature

#66 Feat: DailyLook 댓글 수정 기능 구현
  src/main/java/com/example/fashionlog/controller/DailyLookController.java
  src/main/java/com/example/fashionlog/domain/DailyLookComment.java
  src/main/java/com/example/fashionlog/dto/DailyLookCommentDto.java
  src/main/java/com/example/fashionlog/service/DailyLookService.java
  src/main/resources/templates/dailylook/detail.html
Labels: ✨ feature

#68 Feat: FreeBoard 자유 게시판 댓글 삭제하기 구현 + Soft Delete 방식으로 변경
  src/main/java/com/example/fashionlog/controller/FreeBoardController.java
  src/main/java/com/example/fashionlog/domain/FreeBoard.java
  src/main/java/com/example/fashionlog/domain/FreeBoardComment.java
  src/main/java/com/example/fashionlog/service/FreeBoardService.java
  src/main/resources/templates/freeboard/detail.html
Labels: 💪 enhancement, ✨ feature

#69 Feat: Lookbook 댓글 기능 추가
  src/main/java/com/example/fashionlog/controller/LookbookController.java
  src/main/java/com/example/fashionlog/domain/LookbookComment.java
  src/main/java/com/example/fashionlog/dto/LookbookCommentDto.java
  src/main/java/com/example/fashionlog/repository/LookbookCommentRepository.java
  src/main/java/com/example/fashionlog/service/LookbookService.java
  src/main/resources/templates/lookbook/detail.html
Labels: 📚 documentation, ✨ feature

#70 Feat: DailyLook 댓글 삭제 기능 구현
  src/main/java/com/example/fashionlog/controller/DailyLookController.java
  src/main/java/com/example/fashionlog/domain/DailyLookComment.java
  src/main/java/com/example/fashionlog/repository/DailyLookCommentRepository.java
  src/main/java/com/example/fashionlog/service/DailyLookService.java
  src/main/resources/templates/dailylook/detail.html
Labels: ✨ feature

#72 Refactor: FreeBoard 코드 리팩터링 + Not Null 예외 처리 코드 추가
  src/main/java/com/example/fashionlog/controller/FreeBoardController.java
  src/main/java/com/example/fashionlog/domain/FreeBoard.java
  src/main/java/com/example/fashionlog/domain/FreeBoardComment.java
  src/main/java/com/example/fashionlog/dto/FreeBoardCommentDto.java
  src/main/java/com/example/fashionlog/dto/FreeBoardDto.java
  src/main/java/com/example/fashionlog/service/FreeBoardService.java
  src/main/resources/static/freeboard/css/style.css
  src/main/resources/static/freeboard/js/commentEditForm.js
  src/main/resources/templates/freeboard/detail.html
  src/main/resources/templates/freeboard/edit.html
  src/main/resources/templates/freeboard/form.html
  src/main/resources/templates/freeboard/list.html
Labels: 💪 enhancement, ⚒️ refactor

#74 Document: FreeBoard 코드 주석 처리
  src/main/java/com/example/fashionlog/controller/FreeBoardController.java
  src/main/java/com/example/fashionlog/domain/FreeBoard.java
  src/main/java/com/example/fashionlog/domain/FreeBoardComment.java
  src/main/java/com/example/fashionlog/dto/FreeBoardCommentDto.java
  src/main/java/com/example/fashionlog/dto/FreeBoardDto.java
  src/main/java/com/example/fashionlog/repository/FreeBoardCommentRepository.java
  src/main/java/com/example/fashionlog/repository/FreeBoardRepository.java
  src/main/java/com/example/fashionlog/service/FreeBoardService.java
  src/main/resources/static/freeboard/js/commentEditForm.js
  src/main/resources/static/style.css
  src/main/resources/templates/freeboard/detail.html
  src/main/resources/templates/freeboard/edit.html
  src/main/resources/templates/freeboard/form.html
  src/main/resources/templates/freeboard/list.html
Labels: 📚 documentation

#77 Refactor: FreeBoard Service에서 update, delete 리팩토링
  src/main/java/com/example/fashionlog/service/FreeBoardService.java
Labels: ⚒️ refactor

#78 Refactor: DailyLook 삭제 기능 소프트딜리트로 변경 및 Dto클래스 @Data어노테이션 추가
  src/main/java/com/example/fashionlog/controller/DailyLookController.java
  src/main/java/com/example/fashionlog/domain/DailyLook.java
  src/main/java/com/example/fashionlog/dto/DailyLookCommentDto.java
  src/main/java/com/example/fashionlog/dto/DailyLookDto.java
  src/main/java/com/example/fashionlog/repository/DailyLookRepository.java
  src/main/java/com/example/fashionlog/service/DailyLookService.java
  src/main/resources/templates/dailylook/edit.html
Labels: 🐞 bug, ⚒️ refactor

#79 Docs: Update issue templates
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: 📚 documentation

#81 Feat: InterviewBoard 댓글 작성, 조회 기능 구현
  src/main/java/com/example/fashionlog/controller/InterviewBoardController.java
  src/main/java/com/example/fashionlog/domain/InterviewBoardComment.java
  src/main/java/com/example/fashionlog/dto/InterviewBoardCommentDto.java
  src/main/java/com/example/fashionlog/repository/InterviewBoardCommentRepository.java
  src/main/java/com/example/fashionlog/service/InterviewBoardService.java
  src/main/resources/templates/interviewboard/detail.html
Labels: ✨ feature

#84 Refactor, Design: 스타일 구조 개선 및 공통 스타일 분리
  src/main/resources/static/dailylook/css/detail.css
  src/main/resources/static/dailylook/css/styles.css
  src/main/resources/static/dailylook/js/detail.js
  src/main/resources/templates/dailylook/detail.html
Labels: ⚒️ refactor, 🎨 design

#85 Refactor: InterviewBoard 댓글 작성 오류 수정
  src/main/java/com/example/fashionlog/service/InterviewBoardService.java
  src/main/resources/templates/interviewboard/detail.html
Labels: 🐞 bug, ⚒️ refactor

#83 Docs: Update issue templates
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: 📚 documentation

#88 Feat: 게시글, 댓글 Soft Delete 기능 구현
  src/main/java/com/example/fashionlog/controller/LookbookController.java
  src/main/java/com/example/fashionlog/domain/Lookbook.java
  src/main/java/com/example/fashionlog/domain/LookbookComment.java
  src/main/java/com/example/fashionlog/repository/LookbookCommentRepository.java
  src/main/java/com/example/fashionlog/repository/LookbookRepository.java
  src/main/java/com/example/fashionlog/service/LookbookService.java
  src/main/resources/templates/lookbook/detail.html
  src/main/resources/templates/lookbook/list.html
Labels: ✨ feature

#86 Feat: InterviewBoard 댓글 수정 기능 구현
  src/main/java/com/example/fashionlog/controller/InterviewBoardController.java
  src/main/java/com/example/fashionlog/domain/InterviewBoardComment.java
  src/main/java/com/example/fashionlog/service/InterviewBoardService.java
  src/main/resources/templates/interviewboard/detail.html
Labels: ✨ feature

#89 Feat: InterviewBoard 댓글 삭제 기능 구현
  src/main/java/com/example/fashionlog/controller/InterviewBoardController.java
  src/main/java/com/example/fashionlog/domain/InterviewBoardComment.java
  src/main/java/com/example/fashionlog/service/InterviewBoardService.java
  src/main/resources/templates/interviewboard/detail.html
Labels: ✨ feature

#90 Refactor, Design: edit 스타일 적용
  src/main/resources/static/dailylook/css/edit-form.css
  src/main/resources/templates/dailylook/edit.html
Labels: ⚒️ refactor, 🎨 design

#91 Refactor, Design: detail.html 날짜 표현 로직 변경 및 게시판 각 페이지 스타일 추가
  src/main/resources/static/dailylook/css/detail.css
  src/main/resources/static/dailylook/css/list.css
  src/main/resources/templates/dailylook/detail.html
  src/main/resources/templates/dailylook/edit.html
  src/main/resources/templates/dailylook/form.html
  src/main/resources/templates/dailylook/list.html
Labels: ⚒️ refactor

#93 Refactor: FreeBoard 두 번째 전반적인 리팩토링 + css 추가
  src/main/java/com/example/fashionlog/controller/FreeBoardController.java
  src/main/java/com/example/fashionlog/domain/FreeBoardComment.java
  src/main/java/com/example/fashionlog/dto/FreeBoardCommentDto.java
  src/main/java/com/example/fashionlog/dto/FreeBoardDto.java
  src/main/java/com/example/fashionlog/repository/FreeBoardCommentRepository.java
  src/main/java/com/example/fashionlog/repository/FreeBoardRepository.java
  src/main/java/com/example/fashionlog/service/FreeBoardService.java
  src/main/resources/static/freeboard/css/detail.css
  src/main/resources/static/freeboard/css/edit-form.css
  src/main/resources/static/freeboard/css/style.css
  src/main/resources/static/freeboard/css/styles.css
  src/main/resources/static/freeboard/js/commentEditForm.js
  src/main/resources/static/freeboard/js/detail.js
  src/main/resources/templates/freeboard/detail.html
  src/main/resources/templates/freeboard/edit.html
  src/main/resources/templates/freeboard/form.html
  src/main/resources/templates/freeboard/list.html
Labels: ⚒️ refactor, 🎨 design

#95 Refactor: 게시판 Entity 코드 중복성을 줄이기 위한 Base Entity 사용
  src/main/java/com/example/fashionlog/FashionLogApplication.java
  src/main/java/com/example/fashionlog/domain/BaseEntity.java
  src/main/java/com/example/fashionlog/domain/CommentBaseEntity.java
  src/main/java/com/example/fashionlog/domain/CommentUpdatable.java
  src/main/java/com/example/fashionlog/domain/Updatable.java
Labels: 📚 documentation, ⚒️ refactor

#100 Refactor: FreeBoard 세 번째 전반적인 리팩토링 및 게시글 생성 오류 수정
  src/main/java/com/example/fashionlog/controller/FreeBoardController.java
  src/main/java/com/example/fashionlog/domain/FreeBoard.java
  src/main/java/com/example/fashionlog/domain/FreeBoardComment.java
  src/main/java/com/example/fashionlog/dto/FreeBoardCommentDto.java
  src/main/java/com/example/fashionlog/dto/FreeBoardDto.java
  src/main/java/com/example/fashionlog/repository/FreeBoardRepository.java
  src/main/java/com/example/fashionlog/service/FreeBoardService.java
  src/main/resources/templates/freeboard/form.html
Labels: 🐞 bug, ⚒️ refactor

#102 Refactor: DailyLook 게시판 엔티티에 BaseEntity 상속 및 Dto 에 Updatable 구현
  src/main/java/com/example/fashionlog/controller/DailyLookController.java
  src/main/java/com/example/fashionlog/domain/DailyLook.java
  src/main/java/com/example/fashionlog/domain/DailyLookComment.java
  src/main/java/com/example/fashionlog/dto/DailyLookCommentDto.java
  src/main/java/com/example/fashionlog/dto/DailyLookDto.java
  src/main/java/com/example/fashionlog/repository/DailyLookRepository.java
  src/main/java/com/example/fashionlog/service/DailyLookService.java
Labels: ⚒️ refactor

#104 Refactor: InterviewBoard html, css 리팩토링
  src/main/resources/static/interview/css/detail.css
  src/main/resources/static/interview/css/edit-form.css
  src/main/resources/static/interview/css/list.css
  src/main/resources/static/interview/css/styles.css
  src/main/resources/static/interview/js/detail.js
  src/main/resources/templates/interviewboard/detail.html
  src/main/resources/templates/interviewboard/edit.html
  src/main/resources/templates/interviewboard/form.html
  src/main/resources/templates/interviewboard/list.html
Labels: ⚒️ refactor

#105 Refactor: BaseEntity content 컬럼 속성 추가
  src/main/java/com/example/fashionlog/domain/BaseEntity.java
  src/main/java/com/example/fashionlog/domain/CommentBaseEntity.java
Labels: ⚒️ refactor

#107 Refactor: InterviewBoard 관련 리팩토링
  src/main/java/com/example/fashionlog/domain/InterviewBoard.java
  src/main/java/com/example/fashionlog/domain/InterviewBoardComment.java
  src/main/java/com/example/fashionlog/dto/InterviewBoardCommentDto.java
  src/main/java/com/example/fashionlog/dto/InterviewBoardDto.java
  src/main/java/com/example/fashionlog/repository/InterviewBoardRepository.java
  src/main/java/com/example/fashionlog/service/InterviewBoardService.java
Labels: ⚒️ refactor

#109 Refactor: InterviewBoard 관련 BaseEntity 적용
  src/main/java/com/example/fashionlog/domain/InterviewBoard.java
  src/main/java/com/example/fashionlog/domain/InterviewBoardComment.java
  src/main/java/com/example/fashionlog/dto/InterviewBoardCommentDto.java
  src/main/java/com/example/fashionlog/dto/InterviewBoardDto.java
  src/main/java/com/example/fashionlog/service/InterviewBoardService.java
Labels: ⚒️ refactor

#110 Refactor: form.html 태그 위치 수정
  src/main/resources/templates/dailylook/form.html
Labels: ⚒️ refactor
